{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{ Copyright(c) 2014-2015 Embarcadero Technologies, Inc. }
{                                                       }
{*******************************************************}

/// <summary>Unit that holds functionality relative to process MIME parts from/to a network message</summary>
unit Flickr.System.Net.Mime;

interface

{$SCOPEDENUMS ON}

uses
  System.Classes, System.Sysutils;

type
  /// <summary>Class to manage multipart form data</summary>
  TMultipartFormData = class
  private
    FBoundary: string;
    FLastBoundaryWrited: Boolean;
    FStream: TStringStream;
    procedure AdjustLastBoundary;
    function GenerateBoundary: string;
    function GetFileMIMEType(const AFileName: string): string;
    function GetMimeTypeHeader: string;
    function GetStream: TStringStream;
    procedure WriteStringLn(const AString: string);
  public
    /// <summary>Create a multipart form data object</summary>
    constructor Create;
    destructor Destroy; override;
    /// <summary>Add a form data field</summary>
    procedure AddField(const AField, AValue: string);
    /// <summary>Add a form data file</summary>
    procedure AddFile(const AFieldName, AFilePath: string);
    function GetBodyHeader: string;
    /// <summary>Return mime type to be sent in http headers</summary>
    property MimeTypeHeader: string read GetMimeTypeHeader;
    /// <summary>Property to access to the stream which will be sent</summary>
    property Stream: TStringStream read GetStream;
  end;

implementation

type
  TMimeValue = record
    Key: string;
    Value: string;
  end;

{$REGION 'MIME CONST'}
const
  MimeTypes: array[0..987] of TMimeValue = (
  (Key: 'ez'; Value: 'application/andrew-inset'),
  (Key: 'aw'; Value: 'application/applixware'),
  (Key: 'atom'; Value: 'application/atom+xml'),
  (Key: 'atomcat'; Value: 'application/atomcat+xml'),
  (Key: 'atomsvc'; Value: 'application/atomsvc+xml'),
  (Key: 'ccxml'; Value: 'application/ccxml+xml'),
  (Key: 'cdmia'; Value: 'application/cdmi-capability'),
  (Key: 'cdmic'; Value: 'application/cdmi-container'),
  (Key: 'cdmid'; Value: 'application/cdmi-domain'),
  (Key: 'cdmio'; Value: 'application/cdmi-object'),
  (Key: 'cdmiq'; Value: 'application/cdmi-queue'),
  (Key: 'cu'; Value: 'application/cu-seeme'),
  (Key: 'davmount'; Value: 'application/davmount+xml'),
  (Key: 'dbk'; Value: 'application/docbook+xml'),
  (Key: 'dssc'; Value: 'application/dssc+der'),
  (Key: 'xdssc'; Value: 'application/dssc+xml'),
  (Key: 'ecma'; Value: 'application/ecmascript'),
  (Key: 'emma'; Value: 'application/emma+xml'),
  (Key: 'epub'; Value: 'application/epub+zip'),
  (Key: 'exi'; Value: 'application/exi'),
  (Key: 'pfr'; Value: 'application/font-tdpfr'),
  (Key: 'gml'; Value: 'application/gml+xml'),
  (Key: 'gpx'; Value: 'application/gpx+xml'),
  (Key: 'gxf'; Value: 'application/gxf'),
  (Key: 'stk'; Value: 'application/hyperstudio'),
  (Key: 'ink'; Value: 'application/inkml+xml'),
  (Key: 'inkml'; Value: 'application/inkml+xml'),
  (Key: 'ipfix'; Value: 'application/ipfix'),
  (Key: 'jar'; Value: 'application/java-archive'),
  (Key: 'ser'; Value: 'application/java-serialized-object'),
  (Key: 'class'; Value: 'application/java-vm'),
  (Key: 'js'; Value: 'application/javascript'),
  (Key: 'json'; Value: 'application/json'),
  (Key: 'jsonml'; Value: 'application/jsonml+json'),
  (Key: 'lostxml'; Value: 'application/lost+xml'),
  (Key: 'hqx'; Value: 'application/mac-binhex40'),
  (Key: 'cpt'; Value: 'application/mac-compactpro'),
  (Key: 'mads'; Value: 'application/mads+xml'),
  (Key: 'mrc'; Value: 'application/marc'),
  (Key: 'mrcx'; Value: 'application/marcxml+xml'),
  (Key: 'ma'; Value: 'application/mathematica'),
  (Key: 'nb'; Value: 'application/mathematica'),
  (Key: 'mb'; Value: 'application/mathematica'),
  (Key: 'mathml'; Value: 'application/mathml+xml'),
  (Key: 'mbox'; Value: 'application/mbox'),
  (Key: 'mscml'; Value: 'application/mediaservercontrol+xml'),
  (Key: 'metalink'; Value: 'application/metalink+xml'),
  (Key: 'meta4'; Value: 'application/metalink4+xml'),
  (Key: 'mets'; Value: 'application/mets+xml'),
  (Key: 'mods'; Value: 'application/mods+xml'),
  (Key: 'm21'; Value: 'application/mp21'),
  (Key: 'mp21'; Value: 'application/mp21'),
  (Key: 'mp4s'; Value: 'application/mp4'),
  (Key: 'doc'; Value: 'application/msword'),
  (Key: 'dot'; Value: 'application/msword'),
  (Key: 'mxf'; Value: 'application/mxf'),
  (Key: 'bin'; Value: 'application/octet-stream'),
  (Key: 'bpk'; Value: 'application/octet-stream'),
  (Key: 'class'; Value: 'application/octet-stream'),
  (Key: 'deploy'; Value: 'application/octet-stream'),
  (Key: 'dist'; Value: 'application/octet-stream'),
  (Key: 'distz'; Value: 'application/octet-stream'),
  (Key: 'dmg'; Value: 'application/octet-stream'),
  (Key: 'dms'; Value: 'application/octet-stream'),
  (Key: 'dump'; Value: 'application/octet-stream'),
  (Key: 'elc'; Value: 'application/octet-stream'),
  (Key: 'iso'; Value: 'application/octet-stream'),
  (Key: 'lha'; Value: 'application/octet-stream'),
  (Key: 'lrf'; Value: 'application/octet-stream'),
  (Key: 'lzh'; Value: 'application/octet-stream'),
  (Key: 'mar'; Value: 'application/octet-stream'),
  (Key: 'pkg'; Value: 'application/octet-stream'),
  (Key: 'so'; Value: 'application/octet-stream'),
  (Key: 'oda'; Value: 'application/oda'),
  (Key: 'opf'; Value: 'application/oebps-package+xml'),
  (Key: 'ogx'; Value: 'application/ogg'),
  (Key: 'omdoc'; Value: 'application/omdoc+xml'),
  (Key: 'onetoc'; Value: 'application/onenote'),
  (Key: 'onetoc2'; Value: 'application/onenote'),
  (Key: 'onetmp'; Value: 'application/onenote'),
  (Key: 'onepkg'; Value: 'application/onenote'),
  (Key: 'oxps'; Value: 'application/oxps'),
  (Key: 'xer'; Value: 'application/patch-ops-error+xml'),
  (Key: 'pdf'; Value: 'application/pdf'),
  (Key: 'pgp'; Value: 'application/pgp-encrypted'),
  (Key: 'asc'; Value: 'application/pgp-signature'),
  (Key: 'sig'; Value: 'application/pgp-signature'),
  (Key: 'prf'; Value: 'application/pics-rules'),
  (Key: 'p10'; Value: 'application/pkcs10'),
  (Key: 'p7m'; Value: 'application/pkcs7-mime'),
  (Key: 'p7c'; Value: 'application/pkcs7-mime'),
  (Key: 'p7s'; Value: 'application/pkcs7-signature'),
  (Key: 'p8'; Value: 'application/pkcs8'),
  (Key: 'ac'; Value: 'application/pkix-attr-cert'),
  (Key: 'cer'; Value: 'application/pkix-cert'),
  (Key: 'crl'; Value: 'application/pkix-crl'),
  (Key: 'pkipath'; Value: 'application/pkix-pkipath'),
  (Key: 'pki'; Value: 'application/pkixcmp'),
  (Key: 'pls'; Value: 'application/pls+xml'),
  (Key: 'ai'; Value: 'application/postscript'),
  (Key: 'eps'; Value: 'application/postscript'),
  (Key: 'ps'; Value: 'application/postscript'),
  (Key: 'cww'; Value: 'application/prs.cww'),
  (Key: 'pskcxml'; Value: 'application/pskc+xml'),
  (Key: 'rdf'; Value: 'application/rdf+xml'),
  (Key: 'rif'; Value: 'application/reginfo+xml'),
  (Key: 'rnc'; Value: 'application/relax-ng-compact-syntax'),
  (Key: 'rl'; Value: 'application/resource-lists+xml'),
  (Key: 'rld'; Value: 'application/resource-lists-diff+xml'),
  (Key: 'rs'; Value: 'application/rls-services+xml'),
  (Key: 'gbr'; Value: 'application/rpki-ghostbusters'),
  (Key: 'mft'; Value: 'application/rpki-manifest'),
  (Key: 'roa'; Value: 'application/rpki-roa'),
  (Key: 'rsd'; Value: 'application/rsd+xml'),
  (Key: 'rss'; Value: 'application/rss+xml'),
  (Key: 'rtf'; Value: 'application/rtf'),
  (Key: 'sbml'; Value: 'application/sbml+xml'),
  (Key: 'scq'; Value: 'application/scvp-cv-request'),
  (Key: 'scs'; Value: 'application/scvp-cv-response'),
  (Key: 'spq'; Value: 'application/scvp-vp-request'),
  (Key: 'spp'; Value: 'application/scvp-vp-response'),
  (Key: 'sdp'; Value: 'application/sdp'),
  (Key: 'setpay'; Value: 'application/set-payment-initiation'),
  (Key: 'setreg'; Value: 'application/set-registration-initiation'),
  (Key: 'shf'; Value: 'application/shf+xml'),
  (Key: 'smi'; Value: 'application/smil+xml'),
  (Key: 'smil'; Value: 'application/smil+xml'),
  (Key: 'rq'; Value: 'application/sparql-query'),
  (Key: 'srx'; Value: 'application/sparql-results+xml'),
  (Key: 'gram'; Value: 'application/srgs'),
  (Key: 'grxml'; Value: 'application/srgs+xml'),
  (Key: 'sru'; Value: 'application/sru+xml'),
  (Key: 'ssdl'; Value: 'application/ssdl+xml'),
  (Key: 'ssml'; Value: 'application/ssml+xml'),
  (Key: 'tei'; Value: 'application/tei+xml'),
  (Key: 'teicorpus'; Value: 'application/tei+xml'),
  (Key: 'tfi'; Value: 'application/thraud+xml'),
  (Key: 'tsd'; Value: 'application/timestamped-data'),
  (Key: 'plb'; Value: 'application/vnd.3gpp.pic-bw-large'),
  (Key: 'psb'; Value: 'application/vnd.3gpp.pic-bw-small'),
  (Key: 'pvb'; Value: 'application/vnd.3gpp.pic-bw-var'),
  (Key: 'tcap'; Value: 'application/vnd.3gpp2.tcap'),
  (Key: 'pwn'; Value: 'application/vnd.3m.post-it-notes'),
  (Key: 'aso'; Value: 'application/vnd.accpac.simply.aso'),
  (Key: 'imp'; Value: 'application/vnd.accpac.simply.imp'),
  (Key: 'acu'; Value: 'application/vnd.acucobol'),
  (Key: 'atc'; Value: 'application/vnd.acucorp'),
  (Key: 'acutc'; Value: 'application/vnd.acucorp'),
  (Key: 'air'; Value: 'application/vnd.adobe.air-application-installer-package+zip'),
  (Key: 'fcdt'; Value: 'application/vnd.adobe.formscentral.fcdt'),
  (Key: 'fxp'; Value: 'application/vnd.adobe.fxp'),
  (Key: 'fxpl'; Value: 'application/vnd.adobe.fxp'),
  (Key: 'xdp'; Value: 'application/vnd.adobe.xdp+xml'),
  (Key: 'xfdf'; Value: 'application/vnd.adobe.xfdf'),
  (Key: 'ahead'; Value: 'application/vnd.ahead.space'),
  (Key: 'azf'; Value: 'application/vnd.airzip.filesecure.azf'),
  (Key: 'azs'; Value: 'application/vnd.airzip.filesecure.azs'),
  (Key: 'azw'; Value: 'application/vnd.amazon.ebook'),
  (Key: 'acc'; Value: 'application/vnd.americandynamics.acc'),
  (Key: 'ami'; Value: 'application/vnd.amiga.ami'),
  (Key: 'apk'; Value: 'application/vnd.android.package-archive'),
  (Key: 'cii'; Value: 'application/vnd.anser-web-certificate-issue-initiation'),
  (Key: 'fti'; Value: 'application/vnd.anser-web-funds-transfer-initiation'),
  (Key: 'atx'; Value: 'application/vnd.antix.game-component'),
  (Key: 'mpkg'; Value: 'application/vnd.apple.installer+xml'),
  (Key: 'm3u8'; Value: 'application/vnd.apple.mpegurl'),
  (Key: 'swi'; Value: 'application/vnd.aristanetworks.swi'),
  (Key: 'iota'; Value: 'application/vnd.astraea-software.iota'),
  (Key: 'aep'; Value: 'application/vnd.audiograph'),
  (Key: 'mpm'; Value: 'application/vnd.blueice.multipass'),
  (Key: 'bmi'; Value: 'application/vnd.bmi'),
  (Key: 'rep'; Value: 'application/vnd.businessobjects'),
  (Key: 'cdxml'; Value: 'application/vnd.chemdraw+xml'),
  (Key: 'mmd'; Value: 'application/vnd.chipnuts.karaoke-mmd'),
  (Key: 'cdy'; Value: 'application/vnd.cinderella'),
  (Key: 'cla'; Value: 'application/vnd.claymore'),
  (Key: 'rp9'; Value: 'application/vnd.cloanto.rp9'),
  (Key: 'c4g'; Value: 'application/vnd.clonk.c4group'),
  (Key: 'c4d'; Value: 'application/vnd.clonk.c4group'),
  (Key: 'c4f'; Value: 'application/vnd.clonk.c4group'),
  (Key: 'c4p'; Value: 'application/vnd.clonk.c4group'),
  (Key: 'c4u'; Value: 'application/vnd.clonk.c4group'),
  (Key: 'c11amc'; Value: 'application/vnd.cluetrust.cartomobile-config'),
  (Key: 'c11amz'; Value: 'application/vnd.cluetrust.cartomobile-config-pkg'),
  (Key: 'csp'; Value: 'application/vnd.commonspace'),
  (Key: 'cdbcmsg'; Value: 'application/vnd.contact.cmsg'),
  (Key: 'cmc'; Value: 'application/vnd.cosmocaller'),
  (Key: 'clkx'; Value: 'application/vnd.crick.clicker'),
  (Key: 'clkk'; Value: 'application/vnd.crick.clicker.keyboard'),
  (Key: 'clkp'; Value: 'application/vnd.crick.clicker.palette'),
  (Key: 'clkt'; Value: 'application/vnd.crick.clicker.template'),
  (Key: 'clkw'; Value: 'application/vnd.crick.clicker.wordbank'),
  (Key: 'wbs'; Value: 'application/vnd.criticaltools.wbs+xml'),
  (Key: 'pml'; Value: 'application/vnd.ctc-posml'),
  (Key: 'ppd'; Value: 'application/vnd.cups-ppd'),
  (Key: 'car'; Value: 'application/vnd.curl.car'),
  (Key: 'pcurl'; Value: 'application/vnd.curl.pcurl'),
  (Key: 'dart'; Value: 'application/vnd.dart'),
  (Key: 'rdz'; Value: 'application/vnd.data-vision.rdz'),
  (Key: 'uvf'; Value: 'application/vnd.dece.data'),
  (Key: 'uvvf'; Value: 'application/vnd.dece.data'),
  (Key: 'uvd'; Value: 'application/vnd.dece.data'),
  (Key: 'uvvd'; Value: 'application/vnd.dece.data'),
  (Key: 'uvt'; Value: 'application/vnd.dece.ttml+xml'),
  (Key: 'uvvt'; Value: 'application/vnd.dece.ttml+xml'),
  (Key: 'uvx'; Value: 'application/vnd.dece.unspecified'),
  (Key: 'uvvx'; Value: 'application/vnd.dece.unspecified'),
  (Key: 'uvz'; Value: 'application/vnd.dece.zip'),
  (Key: 'uvvz'; Value: 'application/vnd.dece.zip'),
  (Key: 'fe_launch'; Value: 'application/vnd.denovo.fcselayout-link'),
  (Key: 'dna'; Value: 'application/vnd.dna'),
  (Key: 'mlp'; Value: 'application/vnd.dolby.mlp'),
  (Key: 'dpg'; Value: 'application/vnd.dpgraph'),
  (Key: 'dfac'; Value: 'application/vnd.dreamfactory'),
  (Key: 'kpxx'; Value: 'application/vnd.ds-keypoint'),
  (Key: 'ait'; Value: 'application/vnd.dvb.ait'),
  (Key: 'svc'; Value: 'application/vnd.dvb.service'),
  (Key: 'geo'; Value: 'application/vnd.dynageo'),
  (Key: 'mag'; Value: 'application/vnd.ecowin.chart'),
  (Key: 'nml'; Value: 'application/vnd.enliven'),
  (Key: 'esf'; Value: 'application/vnd.epson.esf'),
  (Key: 'msf'; Value: 'application/vnd.epson.msf'),
  (Key: 'qam'; Value: 'application/vnd.epson.quickanime'),
  (Key: 'slt'; Value: 'application/vnd.epson.salt'),
  (Key: 'ssf'; Value: 'application/vnd.epson.ssf'),
  (Key: 'es3'; Value: 'application/vnd.eszigno3+xml'),
  (Key: 'et3'; Value: 'application/vnd.eszigno3+xml'),
  (Key: 'ez2'; Value: 'application/vnd.ezpix-album'),
  (Key: 'ez3'; Value: 'application/vnd.ezpix-package'),
  (Key: 'fdf'; Value: 'application/vnd.fdf'),
  (Key: 'mseed'; Value: 'application/vnd.fdsn.mseed'),
  (Key: 'seed'; Value: 'application/vnd.fdsn.seed'),
  (Key: 'dataless'; Value: 'application/vnd.fdsn.seed'),
  (Key: 'gph'; Value: 'application/vnd.flographit'),
  (Key: 'ftc'; Value: 'application/vnd.fluxtime.clip'),
  (Key: 'fm'; Value: 'application/vnd.framemaker'),
  (Key: 'frame'; Value: 'application/vnd.framemaker'),
  (Key: 'maker'; Value: 'application/vnd.framemaker'),
  (Key: 'book'; Value: 'application/vnd.framemaker'),
  (Key: 'fnc'; Value: 'application/vnd.frogans.fnc'),
  (Key: 'ltf'; Value: 'application/vnd.frogans.ltf'),
  (Key: 'fsc'; Value: 'application/vnd.fsc.weblaunch'),
  (Key: 'oas'; Value: 'application/vnd.fujitsu.oasys'),
  (Key: 'oa2'; Value: 'application/vnd.fujitsu.oasys2'),
  (Key: 'oa3'; Value: 'application/vnd.fujitsu.oasys3'),
  (Key: 'fg5'; Value: 'application/vnd.fujitsu.oasysgp'),
  (Key: 'bh2'; Value: 'application/vnd.fujitsu.oasysprs'),
  (Key: 'ddd'; Value: 'application/vnd.fujixerox.ddd'),
  (Key: 'xdw'; Value: 'application/vnd.fujixerox.docuworks'),
  (Key: 'xbd'; Value: 'application/vnd.fujixerox.docuworks.binder'),
  (Key: 'fzs'; Value: 'application/vnd.fuzzysheet'),
  (Key: 'txd'; Value: 'application/vnd.genomatix.tuxedo'),
  (Key: 'ggb'; Value: 'application/vnd.geogebra.file'),
  (Key: 'ggt'; Value: 'application/vnd.geogebra.tool'),
  (Key: 'gex'; Value: 'application/vnd.geometry-explorer'),
  (Key: 'gre'; Value: 'application/vnd.geometry-explorer'),
  (Key: 'gxt'; Value: 'application/vnd.geonext'),
  (Key: 'g2w'; Value: 'application/vnd.geoplan'),
  (Key: 'g3w'; Value: 'application/vnd.geospace'),
  (Key: 'gmx'; Value: 'application/vnd.gmx'),
  (Key: 'kml'; Value: 'application/vnd.google-earth.kml+xml'),
  (Key: 'kmz'; Value: 'application/vnd.google-earth.kmz'),
  (Key: 'gqf'; Value: 'application/vnd.grafeq'),
  (Key: 'gqs'; Value: 'application/vnd.grafeq'),
  (Key: 'gac'; Value: 'application/vnd.groove-account'),
  (Key: 'ghf'; Value: 'application/vnd.groove-help'),
  (Key: 'gim'; Value: 'application/vnd.groove-identity-message'),
  (Key: 'grv'; Value: 'application/vnd.groove-injector'),
  (Key: 'gtm'; Value: 'application/vnd.groove-tool-message'),
  (Key: 'tpl'; Value: 'application/vnd.groove-tool-template'),
  (Key: 'vcg'; Value: 'application/vnd.groove-vcard'),
  (Key: 'hal'; Value: 'application/vnd.hal+xml'),
  (Key: 'zmm'; Value: 'application/vnd.handheld-entertainment+xml'),
  (Key: 'hbci'; Value: 'application/vnd.hbci'),
  (Key: 'les'; Value: 'application/vnd.hhe.lesson-player'),
  (Key: 'hpgl'; Value: 'application/vnd.hp-hpgl'),
  (Key: 'hpid'; Value: 'application/vnd.hp-hpid'),
  (Key: 'hps'; Value: 'application/vnd.hp-hps'),
  (Key: 'jlt'; Value: 'application/vnd.hp-jlyt'),
  (Key: 'pcl'; Value: 'application/vnd.hp-pcl'),
  (Key: 'pclxl'; Value: 'application/vnd.hp-pclxl'),
  (Key: 'sfd-hdstx'; Value: 'application/vnd.hydrostatix.sof-data'),
  (Key: 'mpy'; Value: 'application/vnd.ibm.minipay'),
  (Key: 'afp'; Value: 'application/vnd.ibm.modcap'),
  (Key: 'listafp'; Value: 'application/vnd.ibm.modcap'),
  (Key: 'list3820'; Value: 'application/vnd.ibm.modcap'),
  (Key: 'irm'; Value: 'application/vnd.ibm.rights-management'),
  (Key: 'sc'; Value: 'application/vnd.ibm.secure-container'),
  (Key: 'icc'; Value: 'application/vnd.iccprofile'),
  (Key: 'icm'; Value: 'application/vnd.iccprofile'),
  (Key: 'igl'; Value: 'application/vnd.igloader'),
  (Key: 'ivp'; Value: 'application/vnd.immervision-ivp'),
  (Key: 'ivu'; Value: 'application/vnd.immervision-ivu'),
  (Key: 'igm'; Value: 'application/vnd.insors.igm'),
  (Key: 'xpw'; Value: 'application/vnd.intercon.formnet'),
  (Key: 'xpx'; Value: 'application/vnd.intercon.formnet'),
  (Key: 'i2g'; Value: 'application/vnd.intergeo'),
  (Key: 'qbo'; Value: 'application/vnd.intu.qbo'),
  (Key: 'qfx'; Value: 'application/vnd.intu.qfx'),
  (Key: 'rcprofile'; Value: 'application/vnd.ipunplugged.rcprofile'),
  (Key: 'irp'; Value: 'application/vnd.irepository.package+xml'),
  (Key: 'xpr'; Value: 'application/vnd.is-xpr'),
  (Key: 'fcs'; Value: 'application/vnd.isac.fcs'),
  (Key: 'jam'; Value: 'application/vnd.jam'),
  (Key: 'rms'; Value: 'application/vnd.jcp.javame.midlet-rms'),
  (Key: 'jisp'; Value: 'application/vnd.jisp'),
  (Key: 'joda'; Value: 'application/vnd.joost.joda-archive'),
  (Key: 'ktz'; Value: 'application/vnd.kahootz'),
  (Key: 'ktr'; Value: 'application/vnd.kahootz'),
  (Key: 'karbon'; Value: 'application/vnd.kde.karbon'),
  (Key: 'chrt'; Value: 'application/vnd.kde.kchart'),
  (Key: 'kfo'; Value: 'application/vnd.kde.kformula'),
  (Key: 'flw'; Value: 'application/vnd.kde.kivio'),
  (Key: 'kon'; Value: 'application/vnd.kde.kontour'),
  (Key: 'kpr'; Value: 'application/vnd.kde.kpresenter'),
  (Key: 'kpt'; Value: 'application/vnd.kde.kpresenter'),
  (Key: 'ksp'; Value: 'application/vnd.kde.kspread'),
  (Key: 'kwd'; Value: 'application/vnd.kde.kword'),
  (Key: 'kwt'; Value: 'application/vnd.kde.kword'),
  (Key: 'htke'; Value: 'application/vnd.kenameaapp'),
  (Key: 'kia'; Value: 'application/vnd.kidspiration'),
  (Key: 'kne'; Value: 'application/vnd.kinar'),
  (Key: 'knp'; Value: 'application/vnd.kinar'),
  (Key: 'skp'; Value: 'application/vnd.koan'),
  (Key: 'skd'; Value: 'application/vnd.koan'),
  (Key: 'skt'; Value: 'application/vnd.koan'),
  (Key: 'skm'; Value: 'application/vnd.koan'),
  (Key: 'sse'; Value: 'application/vnd.kodak-descriptor'),
  (Key: 'lasxml'; Value: 'application/vnd.las.las+xml'),
  (Key: 'lbd'; Value: 'application/vnd.llamagraphics.life-balance.desktop'),
  (Key: 'lbe'; Value: 'application/vnd.llamagraphics.life-balance.exchange+xml'),
  (Key: '123'; Value: 'application/vnd.lotus-1-2-3'),
  (Key: 'apr'; Value: 'application/vnd.lotus-approach'),
  (Key: 'pre'; Value: 'application/vnd.lotus-freelance'),
  (Key: 'nsf'; Value: 'application/vnd.lotus-notes'),
  (Key: 'org'; Value: 'application/vnd.lotus-organizer'),
  (Key: 'scm'; Value: 'application/vnd.lotus-screencam'),
  (Key: 'lwp'; Value: 'application/vnd.lotus-wordpro'),
  (Key: 'portpkg'; Value: 'application/vnd.macports.portpkg'),
  (Key: 'mcd'; Value: 'application/vnd.mcd'),
  (Key: 'mc1'; Value: 'application/vnd.medcalcdata'),
  (Key: 'cdkey'; Value: 'application/vnd.mediastation.cdkey'),
  (Key: 'mwf'; Value: 'application/vnd.mfer'),
  (Key: 'mfm'; Value: 'application/vnd.mfmp'),
  (Key: 'flo'; Value: 'application/vnd.micrografx.flo'),
  (Key: 'igx'; Value: 'application/vnd.micrografx.igx'),
  (Key: 'mif'; Value: 'application/vnd.mif'),
  (Key: 'daf'; Value: 'application/vnd.mobius.daf'),
  (Key: 'dis'; Value: 'application/vnd.mobius.dis'),
  (Key: 'mbk'; Value: 'application/vnd.mobius.mbk'),
  (Key: 'mqy'; Value: 'application/vnd.mobius.mqy'),
  (Key: 'msl'; Value: 'application/vnd.mobius.msl'),
  (Key: 'plc'; Value: 'application/vnd.mobius.plc'),
  (Key: 'txf'; Value: 'application/vnd.mobius.txf'),
  (Key: 'mpn'; Value: 'application/vnd.mophun.application'),
  (Key: 'mpc'; Value: 'application/vnd.mophun.certificate'),
  (Key: 'xul'; Value: 'application/vnd.mozilla.xul+xml'),
  (Key: 'cil'; Value: 'application/vnd.ms-artgalry'),
  (Key: 'cab'; Value: 'application/vnd.ms-cab-compressed'),
  (Key: 'xls'; Value: 'application/vnd.ms-excel'),
  (Key: 'xlm'; Value: 'application/vnd.ms-excel'),
  (Key: 'xla'; Value: 'application/vnd.ms-excel'),
  (Key: 'xlc'; Value: 'application/vnd.ms-excel'),
  (Key: 'xlt'; Value: 'application/vnd.ms-excel'),
  (Key: 'xlw'; Value: 'application/vnd.ms-excel'),
  (Key: 'xlam'; Value: 'application/vnd.ms-excel.addin.macroenabled.12'),
  (Key: 'xlsb'; Value: 'application/vnd.ms-excel.sheet.binary.macroenabled.12'),
  (Key: 'xlsm'; Value: 'application/vnd.ms-excel.sheet.macroenabled.12'),
  (Key: 'xltm'; Value: 'application/vnd.ms-excel.template.macroenabled.12'),
  (Key: 'eot'; Value: 'application/vnd.ms-fontobject'),
  (Key: 'chm'; Value: 'application/vnd.ms-htmlhelp'),
  (Key: 'ims'; Value: 'application/vnd.ms-ims'),
  (Key: 'lrm'; Value: 'application/vnd.ms-lrm'),
  (Key: 'thmx'; Value: 'application/vnd.ms-officetheme'),
  (Key: 'cat'; Value: 'application/vnd.ms-pki.seccat'),
  (Key: 'stl'; Value: 'application/vnd.ms-pki.stl'),
  (Key: 'ppt'; Value: 'application/vnd.ms-powerpoint'),
  (Key: 'pps'; Value: 'application/vnd.ms-powerpoint'),
  (Key: 'pot'; Value: 'application/vnd.ms-powerpoint'),
  (Key: 'ppam'; Value: 'application/vnd.ms-powerpoint.addin.macroenabled.12'),
  (Key: 'pptm'; Value: 'application/vnd.ms-powerpoint.presentation.macroenabled.12'),
  (Key: 'sldm'; Value: 'application/vnd.ms-powerpoint.slide.macroenabled.12'),
  (Key: 'ppsm'; Value: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12'),
  (Key: 'potm'; Value: 'application/vnd.ms-powerpoint.template.macroenabled.12'),
  (Key: 'mpp'; Value: 'application/vnd.ms-project'),
  (Key: 'mpt'; Value: 'application/vnd.ms-project'),
  (Key: 'docm'; Value: 'application/vnd.ms-word.document.macroenabled.12'),
  (Key: 'dotm'; Value: 'application/vnd.ms-word.template.macroenabled.12'),
  (Key: 'wps'; Value: 'application/vnd.ms-works'),
  (Key: 'wks'; Value: 'application/vnd.ms-works'),
  (Key: 'wcm'; Value: 'application/vnd.ms-works'),
  (Key: 'wdb'; Value: 'application/vnd.ms-works'),
  (Key: 'wpl'; Value: 'application/vnd.ms-wpl'),
  (Key: 'xps'; Value: 'application/vnd.ms-xpsdocument'),
  (Key: 'mseq'; Value: 'application/vnd.mseq'),
  (Key: 'mus'; Value: 'application/vnd.musician'),
  (Key: 'msty'; Value: 'application/vnd.muvee.style'),
  (Key: 'taglet'; Value: 'application/vnd.mynfc'),
  (Key: 'nlu'; Value: 'application/vnd.neurolanguage.nlu'),
  (Key: 'ntf'; Value: 'application/vnd.nitf'),
  (Key: 'nitf'; Value: 'application/vnd.nitf'),
  (Key: 'nnd'; Value: 'application/vnd.noblenet-directory'),
  (Key: 'nns'; Value: 'application/vnd.noblenet-sealer'),
  (Key: 'nnw'; Value: 'application/vnd.noblenet-web'),
  (Key: 'ngdat'; Value: 'application/vnd.nokia.n-gage.data'),
  (Key: 'n-gage'; Value: 'application/vnd.nokia.n-gage.symbian.install'),
  (Key: 'rpst'; Value: 'application/vnd.nokia.radio-preset'),
  (Key: 'rpss'; Value: 'application/vnd.nokia.radio-presets'),
  (Key: 'edm'; Value: 'application/vnd.novadigm.edm'),
  (Key: 'edx'; Value: 'application/vnd.novadigm.edx'),
  (Key: 'ext'; Value: 'application/vnd.novadigm.ext'),
  (Key: 'odc'; Value: 'application/vnd.oasis.opendocument.chart'),
  (Key: 'otc'; Value: 'application/vnd.oasis.opendocument.chart-template'),
  (Key: 'odb'; Value: 'application/vnd.oasis.opendocument.database'),
  (Key: 'odf'; Value: 'application/vnd.oasis.opendocument.formula'),
  (Key: 'odft'; Value: 'application/vnd.oasis.opendocument.formula-template'),
  (Key: 'odg'; Value: 'application/vnd.oasis.opendocument.graphics'),
  (Key: 'otg'; Value: 'application/vnd.oasis.opendocument.graphics-template'),
  (Key: 'odi'; Value: 'application/vnd.oasis.opendocument.image'),
  (Key: 'oti'; Value: 'application/vnd.oasis.opendocument.image-template'),
  (Key: 'odp'; Value: 'application/vnd.oasis.opendocument.presentation'),
  (Key: 'otp'; Value: 'application/vnd.oasis.opendocument.presentation-template'),
  (Key: 'ods'; Value: 'application/vnd.oasis.opendocument.spreadsheet'),
  (Key: 'ots'; Value: 'application/vnd.oasis.opendocument.spreadsheet-template'),
  (Key: 'odt'; Value: 'application/vnd.oasis.opendocument.text'),
  (Key: 'odm'; Value: 'application/vnd.oasis.opendocument.text-master'),
  (Key: 'ott'; Value: 'application/vnd.oasis.opendocument.text-template'),
  (Key: 'oth'; Value: 'application/vnd.oasis.opendocument.text-web'),
  (Key: 'xo'; Value: 'application/vnd.olpc-sugar'),
  (Key: 'dd2'; Value: 'application/vnd.oma.dd2+xml'),
  (Key: 'oxt'; Value: 'application/vnd.openofficeorg.extension'),
  (Key: 'pptx'; Value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation'),
  (Key: 'sldx'; Value: 'application/vnd.openxmlformats-officedocument.presentationml.slide'),
  (Key: 'ppsx'; Value: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'),
  (Key: 'potx'; Value: 'application/vnd.openxmlformats-officedocument.presentationml.template'),
  (Key: 'xlsx'; Value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
  (Key: 'xltx'; Value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template'),
  (Key: 'docx'; Value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'),
  (Key: 'dotx'; Value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'),
  (Key: 'mgp'; Value: 'application/vnd.osgeo.mapguide.package'),
  (Key: 'dp'; Value: 'application/vnd.osgi.dp'),
  (Key: 'esa'; Value: 'application/vnd.osgi.subsystem'),
  (Key: 'pdb'; Value: 'application/vnd.palm'),
  (Key: 'pqa'; Value: 'application/vnd.palm'),
  (Key: 'oprc'; Value: 'application/vnd.palm'),
  (Key: 'paw'; Value: 'application/vnd.pawaafile'),
  (Key: 'str'; Value: 'application/vnd.pg.format'),
  (Key: 'ei6'; Value: 'application/vnd.pg.osasli'),
  (Key: 'efif'; Value: 'application/vnd.picsel'),
  (Key: 'wg'; Value: 'application/vnd.pmi.widget'),
  (Key: 'plf'; Value: 'application/vnd.pocketlearn'),
  (Key: 'pbd'; Value: 'application/vnd.powerbuilder6'),
  (Key: 'box'; Value: 'application/vnd.previewsystems.box'),
  (Key: 'mgz'; Value: 'application/vnd.proteus.magazine'),
  (Key: 'qps'; Value: 'application/vnd.publishare-delta-tree'),
  (Key: 'ptid'; Value: 'application/vnd.pvi.ptid1'),
  (Key: 'qxd'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'qxt'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'qwd'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'qwt'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'qxl'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'qxb'; Value: 'application/vnd.quark.quarkxpress'),
  (Key: 'bed'; Value: 'application/vnd.realvnc.bed'),
  (Key: 'mxl'; Value: 'application/vnd.recordare.musicxml'),
  (Key: 'musicxml'; Value: 'application/vnd.recordare.musicxml+xml'),
  (Key: 'cryptonote'; Value: 'application/vnd.rig.cryptonote'),
  (Key: 'cod'; Value: 'application/vnd.rim.cod'),
  (Key: 'rm'; Value: 'application/vnd.rn-realmedia'),
  (Key: 'rmvb'; Value: 'application/vnd.rn-realmedia-vbr'),
  (Key: 'link66'; Value: 'application/vnd.route66.link66+xml'),
  (Key: 'st'; Value: 'application/vnd.sailingtracker.track'),
  (Key: 'see'; Value: 'application/vnd.seemail'),
  (Key: 'sema'; Value: 'application/vnd.sema'),
  (Key: 'semd'; Value: 'application/vnd.semd'),
  (Key: 'semf'; Value: 'application/vnd.semf'),
  (Key: 'ifm'; Value: 'application/vnd.shana.informed.formdata'),
  (Key: 'itp'; Value: 'application/vnd.shana.informed.formtemplate'),
  (Key: 'iif'; Value: 'application/vnd.shana.informed.interchange'),
  (Key: 'ipk'; Value: 'application/vnd.shana.informed.package'),
  (Key: 'twd'; Value: 'application/vnd.simtech-mindmapper'),
  (Key: 'twds'; Value: 'application/vnd.simtech-mindmapper'),
  (Key: 'mmf'; Value: 'application/vnd.smaf'),
  (Key: 'teacher'; Value: 'application/vnd.smart.teacher'),
  (Key: 'sdkm'; Value: 'application/vnd.solent.sdkm+xml'),
  (Key: 'sdkd'; Value: 'application/vnd.solent.sdkm+xml'),
  (Key: 'dxp'; Value: 'application/vnd.spotfire.dxp'),
  (Key: 'sfs'; Value: 'application/vnd.spotfire.sfs'),
  (Key: 'sdc'; Value: 'application/vnd.stardivision.calc'),
  (Key: 'sda'; Value: 'application/vnd.stardivision.draw'),
  (Key: 'sdd'; Value: 'application/vnd.stardivision.impress'),
  (Key: 'smf'; Value: 'application/vnd.stardivision.math'),
  (Key: 'sdw'; Value: 'application/vnd.stardivision.writer'),
  (Key: 'vor'; Value: 'application/vnd.stardivision.writer'),
  (Key: 'sgl'; Value: 'application/vnd.stardivision.writer-global'),
  (Key: 'smzip'; Value: 'application/vnd.stepmania.package'),
  (Key: 'sm'; Value: 'application/vnd.stepmania.stepchart'),
  (Key: 'sxc'; Value: 'application/vnd.sun.xml.calc'),
  (Key: 'stc'; Value: 'application/vnd.sun.xml.calc.template'),
  (Key: 'sxd'; Value: 'application/vnd.sun.xml.draw'),
  (Key: 'std'; Value: 'application/vnd.sun.xml.draw.template'),
  (Key: 'sxi'; Value: 'application/vnd.sun.xml.impress'),
  (Key: 'sti'; Value: 'application/vnd.sun.xml.impress.template'),
  (Key: 'sxm'; Value: 'application/vnd.sun.xml.math'),
  (Key: 'sxw'; Value: 'application/vnd.sun.xml.writer'),
  (Key: 'sxg'; Value: 'application/vnd.sun.xml.writer.global'),
  (Key: 'stw'; Value: 'application/vnd.sun.xml.writer.template'),
  (Key: 'sus'; Value: 'application/vnd.sus-calendar'),
  (Key: 'susp'; Value: 'application/vnd.sus-calendar'),
  (Key: 'svd'; Value: 'application/vnd.svd'),
  (Key: 'sis'; Value: 'application/vnd.symbian.install'),
  (Key: 'sisx'; Value: 'application/vnd.symbian.install'),
  (Key: 'xsm'; Value: 'application/vnd.syncml+xml'),
  (Key: 'bdm'; Value: 'application/vnd.syncml.dm+wbxml'),
  (Key: 'xdm'; Value: 'application/vnd.syncml.dm+xml'),
  (Key: 'tao'; Value: 'application/vnd.tao.intent-module-archive'),
  (Key: 'pcap'; Value: 'application/vnd.tcpdump.pcap'),
  (Key: 'cap'; Value: 'application/vnd.tcpdump.pcap'),
  (Key: 'dmp'; Value: 'application/vnd.tcpdump.pcap'),
  (Key: 'tmo'; Value: 'application/vnd.tmobile-livetv'),
  (Key: 'tpt'; Value: 'application/vnd.trid.tpt'),
  (Key: 'mxs'; Value: 'application/vnd.triscape.mxs'),
  (Key: 'tra'; Value: 'application/vnd.trueapp'),
  (Key: 'ufd'; Value: 'application/vnd.ufdl'),
  (Key: 'ufdl'; Value: 'application/vnd.ufdl'),
  (Key: 'utz'; Value: 'application/vnd.uiq.theme'),
  (Key: 'umj'; Value: 'application/vnd.umajin'),
  (Key: 'unityweb'; Value: 'application/vnd.unity'),
  (Key: 'uoml'; Value: 'application/vnd.uoml+xml'),
  (Key: 'vcx'; Value: 'application/vnd.vcx'),
  (Key: 'vsd'; Value: 'application/vnd.visio'),
  (Key: 'vst'; Value: 'application/vnd.visio'),
  (Key: 'vss'; Value: 'application/vnd.visio'),
  (Key: 'vsw'; Value: 'application/vnd.visio'),
  (Key: 'vis'; Value: 'application/vnd.visionary'),
  (Key: 'vsf'; Value: 'application/vnd.vsf'),
  (Key: 'wbxml'; Value: 'application/vnd.wap.wbxml'),
  (Key: 'wmlc'; Value: 'application/vnd.wap.wmlc'),
  (Key: 'wmlsc'; Value: 'application/vnd.wap.wmlscriptc'),
  (Key: 'wtb'; Value: 'application/vnd.webturbo'),
  (Key: 'nbp'; Value: 'application/vnd.wolfram.player'),
  (Key: 'wpd'; Value: 'application/vnd.wordperfect'),
  (Key: 'wqd'; Value: 'application/vnd.wqd'),
  (Key: 'stf'; Value: 'application/vnd.wt.stf'),
  (Key: 'xar'; Value: 'application/vnd.xara'),
  (Key: 'xfdl'; Value: 'application/vnd.xfdl'),
  (Key: 'hvd'; Value: 'application/vnd.yamaha.hv-dic'),
  (Key: 'hvs'; Value: 'application/vnd.yamaha.hv-script'),
  (Key: 'hvp'; Value: 'application/vnd.yamaha.hv-voice'),
  (Key: 'osf'; Value: 'application/vnd.yamaha.openscoreformat'),
  (Key: 'osfpvg'; Value: 'application/vnd.yamaha.openscoreformat.osfpvg+xml'),
  (Key: 'saf'; Value: 'application/vnd.yamaha.smaf-audio'),
  (Key: 'spf'; Value: 'application/vnd.yamaha.smaf-phrase'),
  (Key: 'cmp'; Value: 'application/vnd.yellowriver-custom-menu'),
  (Key: 'zir'; Value: 'application/vnd.zul'),
  (Key: 'zirz'; Value: 'application/vnd.zul'),
  (Key: 'zaz'; Value: 'application/vnd.zzazz.deck+xml'),
  (Key: 'vxml'; Value: 'application/voicexml+xml'),
  (Key: 'wgt'; Value: 'application/widget'),
  (Key: 'hlp'; Value: 'application/winhlp'),
  (Key: 'wsdl'; Value: 'application/wsdl+xml'),
  (Key: 'wspolicy'; Value: 'application/wspolicy+xml'),
  (Key: '7z'; Value: 'application/x-7z-compressed'),
  (Key: 'abw'; Value: 'application/x-abiword'),
  (Key: 'ace'; Value: 'application/x-ace-compressed'),
  (Key: 'dmg'; Value: 'application/x-apple-diskimage'),
  (Key: 'aab'; Value: 'application/x-authorware-bin'),
  (Key: 'x32'; Value: 'application/x-authorware-bin'),
  (Key: 'u32'; Value: 'application/x-authorware-bin'),
  (Key: 'vox'; Value: 'application/x-authorware-bin'),
  (Key: 'aam'; Value: 'application/x-authorware-map'),
  (Key: 'aas'; Value: 'application/x-authorware-seg'),
  (Key: 'bcpio'; Value: 'application/x-bcpio'),
  (Key: 'torrent'; Value: 'application/x-bittorrent'),
  (Key: 'blb'; Value: 'application/x-blorb'),
  (Key: 'blorb'; Value: 'application/x-blorb'),
  (Key: 'bz'; Value: 'application/x-bzip'),
  (Key: 'bz2'; Value: 'application/x-bzip2'),
  (Key: 'boz'; Value: 'application/x-bzip2'),
  (Key: 'cbr'; Value: 'application/x-cbr'),
  (Key: 'cba'; Value: 'application/x-cbr'),
  (Key: 'cbt'; Value: 'application/x-cbr'),
  (Key: 'cbz'; Value: 'application/x-cbr'),
  (Key: 'cb7'; Value: 'application/x-cbr'),
  (Key: 'vcd'; Value: 'application/x-cdlink'),
  (Key: 'cfs'; Value: 'application/x-cfs-compressed'),
  (Key: 'chat'; Value: 'application/x-chat'),
  (Key: 'pgn'; Value: 'application/x-chess-pgn'),
  (Key: 'nsc'; Value: 'application/x-conference'),
  (Key: 'cpio'; Value: 'application/x-cpio'),
  (Key: 'csh'; Value: 'application/x-csh'),
  (Key: 'deb'; Value: 'application/x-debian-package'),
  (Key: 'udeb'; Value: 'application/x-debian-package'),
  (Key: 'dgc'; Value: 'application/x-dgc-compressed'),
  (Key: 'dir'; Value: 'application/x-director'),
  (Key: 'dcr'; Value: 'application/x-director'),
  (Key: 'dxr'; Value: 'application/x-director'),
  (Key: 'cst'; Value: 'application/x-director'),
  (Key: 'cct'; Value: 'application/x-director'),
  (Key: 'cxt'; Value: 'application/x-director'),
  (Key: 'w3d'; Value: 'application/x-director'),
  (Key: 'fgd'; Value: 'application/x-director'),
  (Key: 'swa'; Value: 'application/x-director'),
  (Key: 'wad'; Value: 'application/x-doom'),
  (Key: 'ncx'; Value: 'application/x-dtbncx+xml'),
  (Key: 'dtb'; Value: 'application/x-dtbook+xml'),
  (Key: 'res'; Value: 'application/x-dtbresource+xml'),
  (Key: 'dvi'; Value: 'application/x-dvi'),
  (Key: 'evy'; Value: 'application/x-envoy'),
  (Key: 'eva'; Value: 'application/x-eva'),
  (Key: 'bdf'; Value: 'application/x-font-bdf'),
  (Key: 'gsf'; Value: 'application/x-font-ghostscript'),
  (Key: 'psf'; Value: 'application/x-font-linux-psf'),
  (Key: 'otf'; Value: 'application/x-font-otf'),
  (Key: 'pcf'; Value: 'application/x-font-pcf'),
  (Key: 'snf'; Value: 'application/x-font-snf'),
  (Key: 'ttf'; Value: 'application/x-font-ttf'),
  (Key: 'ttc'; Value: 'application/x-font-ttf'),
  (Key: 'pfa'; Value: 'application/x-font-type1'),
  (Key: 'pfb'; Value: 'application/x-font-type1'),
  (Key: 'pfm'; Value: 'application/x-font-type1'),
  (Key: 'afm'; Value: 'application/x-font-type1'),
  (Key: 'woff'; Value: 'application/x-font-woff'),
  (Key: 'arc'; Value: 'application/x-freearc'),
  (Key: 'spl'; Value: 'application/x-futuresplash'),
  (Key: 'gca'; Value: 'application/x-gca-compressed'),
  (Key: 'ulx'; Value: 'application/x-glulx'),
  (Key: 'gnumeric'; Value: 'application/x-gnumeric'),
  (Key: 'gramps'; Value: 'application/x-gramps-xml'),
  (Key: 'gtar'; Value: 'application/x-gtar'),
  (Key: 'hdf'; Value: 'application/x-hdf'),
  (Key: 'install'; Value: 'application/x-install-instructions'),
  (Key: 'iso'; Value: 'application/x-iso9660-image'),
  (Key: 'jnlp'; Value: 'application/x-java-jnlp-file'),
  (Key: 'latex'; Value: 'application/x-latex'),
  (Key: 'lzh'; Value: 'application/x-lzh-compressed'),
  (Key: 'lha'; Value: 'application/x-lzh-compressed'),
  (Key: 'mie'; Value: 'application/x-mie'),
  (Key: 'prc'; Value: 'application/x-mobipocket-ebook'),
  (Key: 'mobi'; Value: 'application/x-mobipocket-ebook'),
  (Key: 'application'; Value: 'application/x-ms-application'),
  (Key: 'lnk'; Value: 'application/x-ms-shortcut'),
  (Key: 'wmd'; Value: 'application/x-ms-wmd'),
  (Key: 'wmz'; Value: 'application/x-ms-wmz'),
  (Key: 'xbap'; Value: 'application/x-ms-xbap'),
  (Key: 'mdb'; Value: 'application/x-msaccess'),
  (Key: 'obd'; Value: 'application/x-msbinder'),
  (Key: 'crd'; Value: 'application/x-mscardfile'),
  (Key: 'clp'; Value: 'application/x-msclip'),
  (Key: 'exe'; Value: 'application/x-msdownload'),
  (Key: 'dll'; Value: 'application/x-msdownload'),
  (Key: 'com'; Value: 'application/x-msdownload'),
  (Key: 'bat'; Value: 'application/x-msdownload'),
  (Key: 'msi'; Value: 'application/x-msdownload'),
  (Key: 'mvb'; Value: 'application/x-msmediaview'),
  (Key: 'm13'; Value: 'application/x-msmediaview'),
  (Key: 'm14'; Value: 'application/x-msmediaview'),
  (Key: 'wmf'; Value: 'application/x-msmetafile'),
  (Key: 'wmz'; Value: 'application/x-msmetafile'),
  (Key: 'emf'; Value: 'application/x-msmetafile'),
  (Key: 'emz'; Value: 'application/x-msmetafile'),
  (Key: 'mny'; Value: 'application/x-msmoney'),
  (Key: 'pub'; Value: 'application/x-mspublisher'),
  (Key: 'scd'; Value: 'application/x-msschedule'),
  (Key: 'trm'; Value: 'application/x-msterminal'),
  (Key: 'wri'; Value: 'application/x-mswrite'),
  (Key: 'nc'; Value: 'application/x-netcdf'),
  (Key: 'cdf'; Value: 'application/x-netcdf'),
  (Key: 'nzb'; Value: 'application/x-nzb'),
  (Key: 'p12'; Value: 'application/x-pkcs12'),
  (Key: 'pfx'; Value: 'application/x-pkcs12'),
  (Key: 'p7b'; Value: 'application/x-pkcs7-certificates'),
  (Key: 'spc'; Value: 'application/x-pkcs7-certificates'),
  (Key: 'p7r'; Value: 'application/x-pkcs7-certreqresp'),
  (Key: 'rar'; Value: 'application/x-rar-compressed'),
  (Key: 'ris'; Value: 'application/x-research-info-systems'),
  (Key: 'sh'; Value: 'application/x-sh'),
  (Key: 'shar'; Value: 'application/x-shar'),
  (Key: 'swf'; Value: 'application/x-shockwave-flash'),
  (Key: 'xap'; Value: 'application/x-silverlight-app'),
  (Key: 'sql'; Value: 'application/x-sql'),
  (Key: 'sit'; Value: 'application/x-stuffit'),
  (Key: 'sitx'; Value: 'application/x-stuffitx'),
  (Key: 'srt'; Value: 'application/x-subrip'),
  (Key: 'sv4cpio'; Value: 'application/x-sv4cpio'),
  (Key: 'sv4crc'; Value: 'application/x-sv4crc'),
  (Key: 't3'; Value: 'application/x-t3vm-image'),
  (Key: 'gam'; Value: 'application/x-tads'),
  (Key: 'tar'; Value: 'application/x-tar'),
  (Key: 'tcl'; Value: 'application/x-tcl'),
  (Key: 'tex'; Value: 'application/x-tex'),
  (Key: 'tfm'; Value: 'application/x-tex-tfm'),
  (Key: 'texinfo'; Value: 'application/x-texinfo'),
  (Key: 'texi'; Value: 'application/x-texinfo'),
  (Key: 'obj'; Value: 'application/x-tgif'),
  (Key: 'ustar'; Value: 'application/x-ustar'),
  (Key: 'src'; Value: 'application/x-wais-source'),
  (Key: 'der'; Value: 'application/x-x509-ca-cert'),
  (Key: 'crt'; Value: 'application/x-x509-ca-cert'),
  (Key: 'fig'; Value: 'application/x-xfig'),
  (Key: 'xlf'; Value: 'application/x-xliff+xml'),
  (Key: 'xpi'; Value: 'application/x-xpinstall'),
  (Key: 'xz'; Value: 'application/x-xz'),
  (Key: 'z1'; Value: 'application/x-zmachine'),
  (Key: 'z2'; Value: 'application/x-zmachine'),
  (Key: 'z3'; Value: 'application/x-zmachine'),
  (Key: 'z4'; Value: 'application/x-zmachine'),
  (Key: 'z5'; Value: 'application/x-zmachine'),
  (Key: 'z6'; Value: 'application/x-zmachine'),
  (Key: 'z7'; Value: 'application/x-zmachine'),
  (Key: 'z8'; Value: 'application/x-zmachine'),
  (Key: 'xaml'; Value: 'application/xaml+xml'),
  (Key: 'xdf'; Value: 'application/xcap-diff+xml'),
  (Key: 'xenc'; Value: 'application/xenc+xml'),
  (Key: 'xhtml'; Value: 'application/xhtml+xml'),
  (Key: 'xht'; Value: 'application/xhtml+xml'),
  (Key: 'xml'; Value: 'application/xml'),
  (Key: 'xsl'; Value: 'application/xml'),
  (Key: 'dtd'; Value: 'application/xml-dtd'),
  (Key: 'xop'; Value: 'application/xop+xml'),
  (Key: 'xpl'; Value: 'application/xproc+xml'),
  (Key: 'xslt'; Value: 'application/xslt+xml'),
  (Key: 'xspf'; Value: 'application/xspf+xml'),
  (Key: 'mxml'; Value: 'application/xv+xml'),
  (Key: 'xhvml'; Value: 'application/xv+xml'),
  (Key: 'xvml'; Value: 'application/xv+xml'),
  (Key: 'xvm'; Value: 'application/xv+xml'),
  (Key: 'yang'; Value: 'application/yang'),
  (Key: 'yin'; Value: 'application/yin+xml'),
  (Key: 'zip'; Value: 'application/zip'),
  (Key: 'adp'; Value: 'audio/adpcm'),
  (Key: 'au'; Value: 'audio/basic'),
  (Key: 'snd'; Value: 'audio/basic'),
  (Key: 'mid'; Value: 'audio/midi'),
  (Key: 'midi'; Value: 'audio/midi'),
  (Key: 'kar'; Value: 'audio/midi'),
  (Key: 'rmi'; Value: 'audio/midi'),
  (Key: 'mp4a'; Value: 'audio/mp4'),
  (Key: 'mpga'; Value: 'audio/mpeg'),
  (Key: 'mp2'; Value: 'audio/mpeg'),
  (Key: 'mp2a'; Value: 'audio/mpeg'),
  (Key: 'mp3'; Value: 'audio/mpeg'),
  (Key: 'm2a'; Value: 'audio/mpeg'),
  (Key: 'm3a'; Value: 'audio/mpeg'),
  (Key: 'oga'; Value: 'audio/ogg'),
  (Key: 'ogg'; Value: 'audio/ogg'),
  (Key: 'spx'; Value: 'audio/ogg'),
  (Key: 's3m'; Value: 'audio/s3m'),
  (Key: 'sil'; Value: 'audio/silk'),
  (Key: 'uva'; Value: 'audio/vnd.dece.audio'),
  (Key: 'uvva'; Value: 'audio/vnd.dece.audio'),
  (Key: 'eol'; Value: 'audio/vnd.digital-winds'),
  (Key: 'dra'; Value: 'audio/vnd.dra'),
  (Key: 'dts'; Value: 'audio/vnd.dts'),
  (Key: 'dtshd'; Value: 'audio/vnd.dts.hd'),
  (Key: 'lvp'; Value: 'audio/vnd.lucent.voice'),
  (Key: 'pya'; Value: 'audio/vnd.ms-playready.media.pya'),
  (Key: 'ecelp4800'; Value: 'audio/vnd.nuera.ecelp4800'),
  (Key: 'ecelp7470'; Value: 'audio/vnd.nuera.ecelp7470'),
  (Key: 'ecelp9600'; Value: 'audio/vnd.nuera.ecelp9600'),
  (Key: 'rip'; Value: 'audio/vnd.rip'),
  (Key: 'weba'; Value: 'audio/webm'),
  (Key: 'aac'; Value: 'audio/x-aac'),
  (Key: 'aif'; Value: 'audio/x-aiff'),
  (Key: 'aiff'; Value: 'audio/x-aiff'),
  (Key: 'aifc'; Value: 'audio/x-aiff'),
  (Key: 'caf'; Value: 'audio/x-caf'),
  (Key: 'flac'; Value: 'audio/x-flac'),
  (Key: 'mka'; Value: 'audio/x-matroska'),
  (Key: 'm3u'; Value: 'audio/x-mpegurl'),
  (Key: 'wax'; Value: 'audio/x-ms-wax'),
  (Key: 'wma'; Value: 'audio/x-ms-wma'),
  (Key: 'ram'; Value: 'audio/x-pn-realaudio'),
  (Key: 'ra'; Value: 'audio/x-pn-realaudio'),
  (Key: 'rmp'; Value: 'audio/x-pn-realaudio-plugin'),
  (Key: 'wav'; Value: 'audio/x-wav'),
  (Key: 'xm'; Value: 'audio/xm'),
  (Key: 'cdx'; Value: 'chemical/x-cdx'),
  (Key: 'cif'; Value: 'chemical/x-cif'),
  (Key: 'cmdf'; Value: 'chemical/x-cmdf'),
  (Key: 'cml'; Value: 'chemical/x-cml'),
  (Key: 'csml'; Value: 'chemical/x-csml'),
  (Key: 'xyz'; Value: 'chemical/x-xyz'),
  (Key: 'bmp'; Value: 'image/bmp'),
  (Key: 'cgm'; Value: 'image/cgm'),
  (Key: 'g3'; Value: 'image/g3fax'),
  (Key: 'gif'; Value: 'image/gif'),
  (Key: 'ief'; Value: 'image/ief'),
  (Key: 'jpeg'; Value: 'image/jpeg'),
  (Key: 'jpg'; Value: 'image/jpeg'),
  (Key: 'jpe'; Value: 'image/jpeg'),
  (Key: 'ktx'; Value: 'image/ktx'),
  (Key: 'png'; Value: 'image/png'),
  (Key: 'btif'; Value: 'image/prs.btif'),
  (Key: 'sgi'; Value: 'image/sgi'),
  (Key: 'svg'; Value: 'image/svg+xml'),
  (Key: 'svgz'; Value: 'image/svg+xml'),
  (Key: 'tiff'; Value: 'image/tiff'),
  (Key: 'tif'; Value: 'image/tiff'),
  (Key: 'psd'; Value: 'image/vnd.adobe.photoshop'),
  (Key: 'uvi'; Value: 'image/vnd.dece.graphic'),
  (Key: 'uvvi'; Value: 'image/vnd.dece.graphic'),
  (Key: 'uvg'; Value: 'image/vnd.dece.graphic'),
  (Key: 'uvvg'; Value: 'image/vnd.dece.graphic'),
  (Key: 'sub'; Value: 'image/vnd.dvb.subtitle'),
  (Key: 'djvu'; Value: 'image/vnd.djvu'),
  (Key: 'djv'; Value: 'image/vnd.djvu'),
  (Key: 'dwg'; Value: 'image/vnd.dwg'),
  (Key: 'dxf'; Value: 'image/vnd.dxf'),
  (Key: 'fbs'; Value: 'image/vnd.fastbidsheet'),
  (Key: 'fpx'; Value: 'image/vnd.fpx'),
  (Key: 'fst'; Value: 'image/vnd.fst'),
  (Key: 'mmr'; Value: 'image/vnd.fujixerox.edmics-mmr'),
  (Key: 'rlc'; Value: 'image/vnd.fujixerox.edmics-rlc'),
  (Key: 'mdi'; Value: 'image/vnd.ms-modi'),
  (Key: 'wdp'; Value: 'image/vnd.ms-photo'),
  (Key: 'npx'; Value: 'image/vnd.net-fpx'),
  (Key: 'wbmp'; Value: 'image/vnd.wap.wbmp'),
  (Key: 'xif'; Value: 'image/vnd.xiff'),
  (Key: 'webp'; Value: 'image/webp'),
  (Key: '3ds'; Value: 'image/x-3ds'),
  (Key: 'ras'; Value: 'image/x-cmu-raster'),
  (Key: 'cmx'; Value: 'image/x-cmx'),
  (Key: 'fh'; Value: 'image/x-freehand'),
  (Key: 'fhc'; Value: 'image/x-freehand'),
  (Key: 'fh4'; Value: 'image/x-freehand'),
  (Key: 'fh5'; Value: 'image/x-freehand'),
  (Key: 'fh7'; Value: 'image/x-freehand'),
  (Key: 'ico'; Value: 'image/x-icon'),
  (Key: 'sid'; Value: 'image/x-mrsid-image'),
  (Key: 'pcx'; Value: 'image/x-pcx'),
  (Key: 'pic'; Value: 'image/x-pict'),
  (Key: 'pct'; Value: 'image/x-pict'),
  (Key: 'pnm'; Value: 'image/x-portable-anymap'),
  (Key: 'pbm'; Value: 'image/x-portable-bitmap'),
  (Key: 'pgm'; Value: 'image/x-portable-graymap'),
  (Key: 'ppm'; Value: 'image/x-portable-pixmap'),
  (Key: 'rgb'; Value: 'image/x-rgb'),
  (Key: 'tga'; Value: 'image/x-tga'),
  (Key: 'xbm'; Value: 'image/x-xbitmap'),
  (Key: 'xpm'; Value: 'image/x-xpixmap'),
  (Key: 'xwd'; Value: 'image/x-xwindowdump'),
  (Key: 'eml'; Value: 'message/rfc822'),
  (Key: 'mime'; Value: 'message/rfc822'),
  (Key: 'igs'; Value: 'model/iges'),
  (Key: 'iges'; Value: 'model/iges'),
  (Key: 'msh'; Value: 'model/mesh'),
  (Key: 'mesh'; Value: 'model/mesh'),
  (Key: 'silo'; Value: 'model/mesh'),
  (Key: 'dae'; Value: 'model/vnd.collada+xml'),
  (Key: 'dwf'; Value: 'model/vnd.dwf'),
  (Key: 'gdl'; Value: 'model/vnd.gdl'),
  (Key: 'gtw'; Value: 'model/vnd.gtw'),
  (Key: 'mts'; Value: 'model/vnd.mts'),
  (Key: 'vtu'; Value: 'model/vnd.vtu'),
  (Key: 'wrl'; Value: 'model/vrml'),
  (Key: 'vrml'; Value: 'model/vrml'),
  (Key: 'x3db'; Value: 'model/x3d+binary'),
  (Key: 'x3dbz'; Value: 'model/x3d+binary'),
  (Key: 'x3dv'; Value: 'model/x3d+vrml'),
  (Key: 'x3dvz'; Value: 'model/x3d+vrml'),
  (Key: 'x3d'; Value: 'model/x3d+xml'),
  (Key: 'x3dz'; Value: 'model/x3d+xml'),
  (Key: 'appcache'; Value: 'text/cache-manifest'),
  (Key: 'ics'; Value: 'text/calendar'),
  (Key: 'ifb'; Value: 'text/calendar'),
  (Key: 'css'; Value: 'text/css'),
  (Key: 'csv'; Value: 'text/csv'),
  (Key: 'html'; Value: 'text/html'),
  (Key: 'htm'; Value: 'text/html'),
  (Key: 'n3'; Value: 'text/n3'),
  (Key: 'txt'; Value: 'text/plain'),
  (Key: 'text'; Value: 'text/plain'),
  (Key: 'conf'; Value: 'text/plain'),
  (Key: 'def'; Value: 'text/plain'),
  (Key: 'list'; Value: 'text/plain'),
  (Key: 'log'; Value: 'text/plain'),
  (Key: 'in'; Value: 'text/plain'),
  (Key: 'dsc'; Value: 'text/prs.lines.tag'),
  (Key: 'rtx'; Value: 'text/richtext'),
  (Key: 'sgml'; Value: 'text/sgml'),
  (Key: 'sgm'; Value: 'text/sgml'),
  (Key: 'tsv'; Value: 'text/tab-separated-values'),
  (Key: 't'; Value: 'text/troff'),
  (Key: 'tr'; Value: 'text/troff'),
  (Key: 'roff'; Value: 'text/troff'),
  (Key: 'man'; Value: 'text/troff'),
  (Key: 'me'; Value: 'text/troff'),
  (Key: 'ms'; Value: 'text/troff'),
  (Key: 'ttl'; Value: 'text/turtle'),
  (Key: 'uri'; Value: 'text/uri-list'),
  (Key: 'uris'; Value: 'text/uri-list'),
  (Key: 'urls'; Value: 'text/uri-list'),
  (Key: 'vcard'; Value: 'text/vcard'),
  (Key: 'curl'; Value: 'text/vnd.curl'),
  (Key: 'dcurl'; Value: 'text/vnd.curl.dcurl'),
  (Key: 'scurl'; Value: 'text/vnd.curl.scurl'),
  (Key: 'mcurl'; Value: 'text/vnd.curl.mcurl'),
  (Key: 'sub'; Value: 'text/vnd.dvb.subtitle'),
  (Key: 'fly'; Value: 'text/vnd.fly'),
  (Key: 'flx'; Value: 'text/vnd.fmi.flexstor'),
  (Key: 'gv'; Value: 'text/vnd.graphviz'),
  (Key: '3dml'; Value: 'text/vnd.in3d.3dml'),
  (Key: 'spot'; Value: 'text/vnd.in3d.spot'),
  (Key: 'jad'; Value: 'text/vnd.sun.j2me.app-descriptor'),
  (Key: 'wml'; Value: 'text/vnd.wap.wml'),
  (Key: 'wmls'; Value: 'text/vnd.wap.wmlscript'),
  (Key: 's'; Value: 'text/x-asm'),
  (Key: 'asm'; Value: 'text/x-asm'),
  (Key: 'c'; Value: 'text/x-c'),
  (Key: 'cc'; Value: 'text/x-c'),
  (Key: 'cxx'; Value: 'text/x-c'),
  (Key: 'cpp'; Value: 'text/x-c'),
  (Key: 'h'; Value: 'text/x-c'),
  (Key: 'hh'; Value: 'text/x-c'),
  (Key: 'dic'; Value: 'text/x-c'),
  (Key: 'f'; Value: 'text/x-fortran'),
  (Key: 'for'; Value: 'text/x-fortran'),
  (Key: 'f77'; Value: 'text/x-fortran'),
  (Key: 'f90'; Value: 'text/x-fortran'),
  (Key: 'java'; Value: 'text/x-java-source'),
  (Key: 'opml'; Value: 'text/x-opml'),
  (Key: 'p'; Value: 'text/x-pascal'),
  (Key: 'pas'; Value: 'text/x-pascal'),
  (Key: 'nfo'; Value: 'text/x-nfo'),
  (Key: 'etx'; Value: 'text/x-setext'),
  (Key: 'sfv'; Value: 'text/x-sfv'),
  (Key: 'uu'; Value: 'text/x-uuencode'),
  (Key: 'vcs'; Value: 'text/x-vcalendar'),
  (Key: 'vcf'; Value: 'text/x-vcard'),
  (Key: '3gp'; Value: 'video/3gpp'),
  (Key: '3g2'; Value: 'video/3gpp2'),
  (Key: 'h261'; Value: 'video/h261'),
  (Key: 'h263'; Value: 'video/h263'),
  (Key: 'h264'; Value: 'video/h264'),
  (Key: 'jpgv'; Value: 'video/jpeg'),
  (Key: 'jpm'; Value: 'video/jpm'),
  (Key: 'jpgm'; Value: 'video/jpm'),
  (Key: 'mj2'; Value: 'video/mj2'),
  (Key: 'mjp2'; Value: 'video/mj2'),
  (Key: 'mp4'; Value: 'video/mp4'),
  (Key: 'mp4v'; Value: 'video/mp4'),
  (Key: 'mpg4'; Value: 'video/mp4'),
  (Key: 'mpeg'; Value: 'video/mpeg'),
  (Key: 'mpg'; Value: 'video/mpeg'),
  (Key: 'mpe'; Value: 'video/mpeg'),
  (Key: 'm1v'; Value: 'video/mpeg'),
  (Key: 'm2v'; Value: 'video/mpeg'),
  (Key: 'ogv'; Value: 'video/ogg'),
  (Key: 'qt'; Value: 'video/quicktime'),
  (Key: 'mov'; Value: 'video/quicktime'),
  (Key: 'uvh'; Value: 'video/vnd.dece.hd'),
  (Key: 'uvvh'; Value: 'video/vnd.dece.hd'),
  (Key: 'uvm'; Value: 'video/vnd.dece.mobile'),
  (Key: 'uvvm'; Value: 'video/vnd.dece.mobile'),
  (Key: 'uvp'; Value: 'video/vnd.dece.pd'),
  (Key: 'uvvp'; Value: 'video/vnd.dece.pd'),
  (Key: 'uvs'; Value: 'video/vnd.dece.sd'),
  (Key: 'uvvs'; Value: 'video/vnd.dece.sd'),
  (Key: 'uvv'; Value: 'video/vnd.dece.video'),
  (Key: 'uvvv'; Value: 'video/vnd.dece.video'),
  (Key: 'dvb'; Value: 'video/vnd.dvb.file'),
  (Key: 'fvt'; Value: 'video/vnd.fvt'),
  (Key: 'mxu'; Value: 'video/vnd.mpegurl'),
  (Key: 'm4u'; Value: 'video/vnd.mpegurl'),
  (Key: 'pyv'; Value: 'video/vnd.ms-playready.media.pyv'),
  (Key: 'uvu'; Value: 'video/vnd.uvvu.mp4'),
  (Key: 'uvvu'; Value: 'video/vnd.uvvu.mp4'),
  (Key: 'viv'; Value: 'video/vnd.vivo'),
  (Key: 'webm'; Value: 'video/webm'),
  (Key: 'f4v'; Value: 'video/x-f4v'),
  (Key: 'fli'; Value: 'video/x-fli'),
  (Key: 'flv'; Value: 'video/x-flv'),
  (Key: 'm4v'; Value: 'video/x-m4v'),
  (Key: 'mkv'; Value: 'video/x-matroska'),
  (Key: 'mk3d'; Value: 'video/x-matroska'),
  (Key: 'mks'; Value: 'video/x-matroska'),
  (Key: 'mng'; Value: 'video/x-mng'),
  (Key: 'asf'; Value: 'video/x-ms-asf'),
  (Key: 'asx'; Value: 'video/x-ms-asf'),
  (Key: 'vob'; Value: 'video/x-ms-vob'),
  (Key: 'wm'; Value: 'video/x-ms-wm'),
  (Key: 'wmv'; Value: 'video/x-ms-wmv'),
  (Key: 'wmx'; Value: 'video/x-ms-wmx'),
  (Key: 'wvx'; Value: 'video/x-ms-wvx'),
  (Key: 'avi'; Value: 'video/x-msvideo'),
  (Key: 'movie'; Value: 'video/x-sgi-movie'),
  (Key: 'smv'; Value: 'video/x-smv'),
  (Key: 'ice'; Value: 'x-conference/x-cooltalk') );
{$ENDREGION}

{ TMultipartFormData }

constructor TMultipartFormData.Create;
begin
  inherited Create;
  FBoundary := GenerateBoundary;
  FStream := TStringStream.Create('', TEncoding.UTF8);
end;

destructor TMultipartFormData.Destroy;
begin
  FStream.Free;
  inherited;
end;

procedure TMultipartFormData.AddField(const AField, AValue: string);
begin
  AdjustLastBoundary;
  WriteStringLn('--' + FBoundary);
  WriteStringLn('Content-Disposition: form-data; name="' + AField + '"');
  WriteStringLn('Content-Type: text/plain');
  //application/octet-stream
  WriteStringLn('');
  WriteStringLn(AValue);
end;

procedure TMultipartFormData.AddFile(const AFieldName, AFilePath: string);
var
  LFileStream: TFileStream;
begin
  AdjustLastBoundary;
  WriteStringLn('--' + FBoundary);
  WriteStringLn('Content-Disposition: form-data; name="' + AFieldName + '"; filename="' + ExtractFileName(AFilePath) + '"');
  WriteStringLn('Content-Type: ' + GetFileMIMEType(AFilePath));
  //WriteStringLn('Content-Transfer-Encoding: binary');
  WriteStringLn('');
  LFileStream := TFileStream.Create(AFilePath, fmOpenRead or fmShareDenyWrite);
  try
    LFileStream.Position := 0;
    //WriteStringLn(TIdEncoderQuotedPrintable.EncodeStream(LFileStream, LFileStream.Size));
    FStream.CopyFrom(LFileStream, LFileStream.Size);
  finally
    LFileStream.Free;
  end;
  WriteStringLn('');
end;

procedure TMultipartFormData.AdjustLastBoundary;
begin
  if FLastBoundaryWrited then
  begin
    FStream.Position := FStream.Size - (Length(FBoundary) + 4);
    FLastBoundaryWrited := False;
  end;
end;

function TMultipartFormData.GenerateBoundary: string;
begin
  Randomize;
  //Result := '-------Embt-Boundary--' + IntToHex(Random(MaxInt), 8) + IntToHex(Random(MaxInt), 8);
  //Result := '--' + IntToHex(Random(MaxInt), 8) + IntToHex(Random(MaxInt), 8);
  Result := 'Boundary_' + FormatDateTime('yyyyMMddhhmmsszzz', Now);
end;

function TMultipartFormData.GetBodyHeader: string;
begin
  GetStream;
  Result := 'POST /services/upload/ HTTP/1.1'#13#10 +
    'Content-Type: multipart/form-data; boundary=' + FBoundary + #13#10 +
    'Host: api.flickr.com'#13#10 +
//    'Timeout: 100'#13#10 +
//    'Accept: */*'#13#10 +
//    'accept-charset: UTF-8' + #13#10 +
    'Content-Length: ' + IntToStr(FStream.Size) + #13#10#13#10;
end;

function TMultipartFormData.GetFileMIMEType(const AFileName: string): string;
var
  I: Integer;
  Ext: string;
begin
  Result := 'application/octet-stream';
  Ext := ExtractFileExt(AFileName).Substring(1);
  for I := 0 to High(MimeTypes) do
    if CompareText(MimeTypes[I].Key, Ext) = 0 then
      Exit(MimeTypes[I].Value);
end;

function TMultipartFormData.GetMimeTypeHeader: string;
begin
  Result := 'multipart/form-data; boundary=' + FBoundary;
end;

function TMultipartFormData.GetStream: TStringStream;
begin
  if not FLastBoundaryWrited then
  begin
    WriteStringLn('--' + FBoundary + '--');
    FLastBoundaryWrited := True;
    //FStream.Size := FStream.Size - 2; not sure if we need this
  end;
  Result := FStream;
end;

procedure TMultipartFormData.WriteStringLn(const AString: string);
var
  Buff: TBytes;
begin
  Buff := TEncoding.UTF8.GetBytes(AString + #13#10);
  FStream.WriteBuffer(Buff, Length(Buff));
end;

end.
